### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by UrbanSide** [n0uur/GhostHunterCorp-SaveEditor#2]
Can you update to new game version?
There seems to have changed the file type from sav to save

**Comment by n0uur** [comment]
I'll try. If I can I will update a release in a few days.

UPDATE 1: I may don't have any time to work on this problem until this new year, I need to close this year project before deadline :( so my boss don't kill me.
but you still can edit old version savefile and let the game migrate your game save into newer version.

**Comment by UrbanSide** [comment]
> I'll try. If I can I will update a release in a few days.
> 
> UPDATE 1: I may don't have any time to work on this problem until this new year, I need to close this year project before deadline :( so my boss don't kill me. but you still can edit old version savefile and let the game migrate your game save into newer version.

i dont have save on old version))

**Comment by masterhyp** [comment]
> > I'll try. If I can I will update a release in a few days.
> > UPDATE 1: I may don't have any time to work on this problem until this new year, I need to close this year project before deadline :( so my boss don't kill me. but you still can edit old version savefile and let the game migrate your game save into newer version.
> 
> i dont have save on old version))

me 2 i would like this to be updated asap

**Comment by n0uur** [comment]
> > I'll try. If I can I will update a release in a few days.
> > UPDATE 1: I may don't have any time to work on this problem until this new year, I need to close this year project before deadline :( so my boss don't kill me. but you still can edit old version savefile and let the game migrate your game save into newer version.
> 
> i dont have save on old version))

You can create old save file using this save editor, just modify value from default value and save.

**Comment by n0uur** [comment]
> 

Last month, the debugging plugin that I use still did not support the current game version of Unity. I'll try again in a few days. :)

This project is now just a side project for me, so don't expect me to give much time to it.

**Comment by masterhyp** [comment]
> > 
> 
> Last month, the debugging plugin that I use still did not support the current game version of Unity. I'll try again in a few days. :)
> 
> This project is now just a side project for me, so don't expect me to give much time to it.

Its ok take your time. I appreciate it

**Comment by n0uur** [comment]
Update:
Good news! I got all save file decrypted and I just analyzed all of it content
I will update the save editor to the newer version in the next weekend :)

**Comment by masterhyp** [comment]
What a legend

**Comment by n0uur** [comment]
😃 
![image](https://user-images.githubusercontent.com/50010805/226767014-2bc3c961-86ce-4be6-aa2f-933009125ead.png)

**Comment by n0uur** [comment]
Published new release, Please check [Release](https://github.com/n0uur/GhostHunterCorp-SaveEditor/releases) section for lateset update :)
